---

- hosts: all
  become: true
  pre_tasks:

  - name: Install updates (Fedora)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution in ["RHEL", "Fedora"]

  - name: Install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]

- hosts: web_servers
  become: true
  tasks:

  - name: Install apache2 and php support packages for Ubuntu
    tags: apache,apache2,ubuntu
    apt: 
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: Install apache2 and php support packages for Fedora
    tags: apache,httpd,fedora
    dnf: 
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution in ["RHEL", "Fedora"]

- hosts: db_servers
  become: true
  tasks:

  - name: Install mariadb package (Fedora)
    tags: mariadb,fedora,db
    dnf:
      name: mariadb-server
      state: latest
    when: ansible_distribution in ["RHEL", "Fedora"]

  - name: Install mariadb package (Ubuntu)
    tags: mariadb,ubuntu,db
    dnf:
      name: mariadb-server
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]

- hosts: file_servers
  become: true
  tasks:

  - name: Install samba package
    tags: samba
    package:
      name: samba
      state: latest