---

- hosts: all
  become: true
  pre_tasks:

  - name: Install updates (Fedora)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution in ["RHEL", "Fedora"]

  - name: Install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]

- hosts: workstations
  become: true
  tasks:

  - name: Install unzip
    package:
      name: unzip

  - name: Install terraform
    unarchive:
      #src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      src: https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: true
  tasks:

  - name: Install apache2 and php support packages for Ubuntu
    tags: apache,apache2,ubuntu
    apt: 
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: Install apache2 and php support packages for Fedora
    tags: apache,httpd,fedora
    dnf: 
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution in ["RHEL", "Fedora"]

  - name: Copy default html file for site
    tags: apache,apache2,httpd
    copy:
      # Directory 'files' is implicit in this case
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: Install mariadb package (Fedora)
    tags: mariadb,fedora,db
    dnf:
      name: mariadb-server
      state: latest
    when: ansible_distribution in ["RHEL", "Fedora"]

  - name: Install mariadb package (Ubuntu)
    tags: mariadb,ubuntu,db
    dnf:
      name: mariadb-server
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]

- hosts: file_servers
  become: true
  tasks:

  - name: Install samba package
    tags: samba
    package:
      name: samba
      state: latest